version: '3.7'

services:
  db:
    image: mongo
    container_name: mongo_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: paulowin
    ports:
      - 27017:27017
  db-admin:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
        - 8081:8081
    depends_on:
        - db
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: paulowin
        ME_CONFIG_MONGODB_SERVER: db